/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package usuario_interface;

import domain.Empleado;
import domain.Liquidacion;
import java.awt.Color;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.Locale;
import javax.swing.JOptionPane;

/**
 *
 * @author andre
 */
public class LiquidarEmpleado extends javax.swing.JFrame {

    /**
     * Crean las instancias
     */
    Liquidacion li = new Liquidacion();
    SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
    Locale locale = new Locale("es", "CO");
    NumberFormat numberFormat = NumberFormat.getNumberInstance(locale);
    int poscision;

    /**
     * Se pasa como argumento al constructor el arreglo empleados para manter la
     * direccion del memoria entre instancias
     */
    public LiquidarEmpleado(Empleado[] empleados) {
        this();
        li.modificarEmpleados(empleados);
    }

    public LiquidarEmpleado() {
        initComponents();
        /**
         * Se desahabilitan los siguientes item
         */
        idEmpleado.setEnabled(true);
        nombre.setEnabled(false);
        sueldo.setEnabled(false);
        fechaIngreso.setEnabled(false);
        fechaRetiro.setEnabled(false);
        primaServicio.setEnabled(false);
        cesantias.setEnabled(false);
        interesesCesantia.setEnabled(false);
        vacaciones.setEnabled(false);
        totalLiquidacion.setEnabled(false);
        precargarLiquidacion.setEnabled(false);
        guardarLiquidacion.setEnabled(false);
        nombre.setDisabledTextColor(Color.black);
        sueldo.setDisabledTextColor(Color.black);
        fechaIngreso.setDisabledTextColor(Color.black);
        fechaRetiro.setDisabledTextColor(Color.black);
        primaServicio.setDisabledTextColor(Color.black);
        cesantias.setDisabledTextColor(Color.black);
        interesesCesantia.setDisabledTextColor(Color.black);
        vacaciones.setDisabledTextColor(Color.black);
        totalLiquidacion.setDisabledTextColor(Color.black);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        idEmpleado = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cargarEnpleado = new javax.swing.JButton();
        fechaIngreso = new javax.swing.JFormattedTextField();
        sueldo = new javax.swing.JFormattedTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        fechaRetiro = new javax.swing.JFormattedTextField();
        precargarLiquidacion = new javax.swing.JButton();
        guardarLiquidacion = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        primaServicio = new javax.swing.JFormattedTextField();
        cesantias = new javax.swing.JFormattedTextField();
        interesesCesantia = new javax.swing.JFormattedTextField();
        vacaciones = new javax.swing.JFormattedTextField();
        totalLiquidacion = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel1.setText("LIQUIDACION DE PRESTACIONES SOCIALES");

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel10.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel10.setText("Identificacion empleado");

        idEmpleado.setBackground(new java.awt.Color(255, 255, 255));
        idEmpleado.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        idEmpleado.setForeground(new java.awt.Color(0, 0, 0));

        jLabel2.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        jLabel2.setText("Nombre empleado");

        nombre.setBackground(new java.awt.Color(255, 255, 255));
        nombre.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        nombre.setForeground(new java.awt.Color(0, 0, 0));

        jLabel3.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        jLabel3.setText("Sueldo");

        jLabel4.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        jLabel4.setText("Fecha de ingreso");

        cargarEnpleado.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        cargarEnpleado.setText("CARGAR EMPLEADO");
        cargarEnpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarEnpleadoActionPerformed(evt);
            }
        });

        fechaIngreso.setBackground(new java.awt.Color(255, 255, 255));
        fechaIngreso.setForeground(new java.awt.Color(0, 0, 0));
        fechaIngreso.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        fechaIngreso.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N

        sueldo.setBackground(new java.awt.Color(255, 255, 255));
        sueldo.setForeground(new java.awt.Color(0, 0, 0));
        sueldo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        sueldo.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(idEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addComponent(nombre)
                    .addComponent(fechaIngreso)
                    .addComponent(sueldo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cargarEnpleado)
                .addGap(40, 40, 40))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(idEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(sueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(cargarEnpleado)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(fechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        jLabel5.setText("Fecha de salida (dd/MM/yy)");

        jLabel6.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        jLabel6.setText("Prima de servicio");

        jLabel7.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        jLabel7.setText("Cesantias");

        jLabel8.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        jLabel8.setText("Intereses de cesantias");

        jLabel9.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        jLabel9.setText("Vacaciones");

        jLabel11.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        jLabel11.setText("Total liquidar");

        fechaRetiro.setBackground(new java.awt.Color(255, 255, 255));
        fechaRetiro.setForeground(new java.awt.Color(0, 0, 0));
        fechaRetiro.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        fechaRetiro.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N

        precargarLiquidacion.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        precargarLiquidacion.setText("PRECARGAR LIQUIDACION");
        precargarLiquidacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precargarLiquidacionActionPerformed(evt);
            }
        });

        guardarLiquidacion.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        guardarLiquidacion.setText("GENERAR LIQUIDACION");
        guardarLiquidacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarLiquidacionActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        jButton1.setText("SALIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        primaServicio.setBackground(new java.awt.Color(255, 255, 255));
        primaServicio.setForeground(new java.awt.Color(0, 0, 0));
        primaServicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        primaServicio.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N

        cesantias.setBackground(new java.awt.Color(255, 255, 255));
        cesantias.setForeground(new java.awt.Color(0, 0, 0));
        cesantias.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        cesantias.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N

        interesesCesantia.setBackground(new java.awt.Color(255, 255, 255));
        interesesCesantia.setForeground(new java.awt.Color(0, 0, 0));
        interesesCesantia.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        interesesCesantia.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N

        vacaciones.setBackground(new java.awt.Color(255, 255, 255));
        vacaciones.setForeground(new java.awt.Color(0, 0, 0));
        vacaciones.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        vacaciones.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N

        totalLiquidacion.setBackground(new java.awt.Color(255, 255, 255));
        totalLiquidacion.setForeground(new java.awt.Color(0, 0, 0));
        totalLiquidacion.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        totalLiquidacion.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cesantias, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                    .addComponent(fechaRetiro)
                    .addComponent(primaServicio)
                    .addComponent(interesesCesantia)
                    .addComponent(vacaciones)
                    .addComponent(totalLiquidacion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(precargarLiquidacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(guardarLiquidacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(100, 100, 100))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(fechaRetiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(precargarLiquidacion)
                    .addComponent(jLabel6)
                    .addComponent(primaServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(cesantias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(guardarLiquidacion)
                    .addComponent(interesesCesantia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(6, 6, 6))
                    .addComponent(vacaciones, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(39, 39, 39))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totalLiquidacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(jLabel1)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guardarLiquidacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarLiquidacionActionPerformed
        /**
         * En el este if se verifica si al usuario ya se le ha generado una
         * liquidacion usando atributo estadoLiquidacion que almacena un valor
         * false si no se le ha generado, y verdad si de lo contrario
         */
        if (li.getEmpleados(poscision).isEstadoLiquidacion() == false) {

            /**
             * Se hace el llamdo al metodo generarLiquidacion que almacena los
             * valor en los respectivos atributos del empleado
             */
            li.generarLiquidacion(poscision);
            idEmpleado.setEnabled(true);
            fechaRetiro.setEnabled(false);
            precargarLiquidacion.setEnabled(false);
            guardarLiquidacion.setEnabled(false);
            idEmpleado.setText("");
            nombre.setText("");
            sueldo.setText("");
            fechaIngreso.setText("");
            fechaRetiro.setText("");
            primaServicio.setText("");
            cesantias.setText("");
            interesesCesantia.setText("");
            vacaciones.setText("");
            totalLiquidacion.setText("");
            JOptionPane.showMessageDialog(null, "Liquidacion generada con exito");
        } else {
            JOptionPane.showMessageDialog(null, "UPSS.. Usario ya se le genero la liquidacion: intento con otro");
            precargarLiquidacion.setEnabled(false);
            guardarLiquidacion.setEnabled(false);
            idEmpleado.setText("");
            nombre.setText("");
            sueldo.setText("");
            fechaIngreso.setText("");
            fechaRetiro.setText("");
            primaServicio.setText("");
            cesantias.setText("");
            interesesCesantia.setText("");
            vacaciones.setText("");
            totalLiquidacion.setText("");
        }
    }//GEN-LAST:event_guardarLiquidacionActionPerformed

    private void cargarEnpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarEnpleadoActionPerformed
        try {
            /**
             * Se realiza un llamdo al metodo buscar para que devuela la poscion
             * en el arreglo de el valor buscado si retorna la poscion correcta
             * muestra los valores de este arreglo, si no devuelve -1 luego se
             * valida para mostrar la informacion en la ventana en sus
             * respectivos campos
             */
            poscision = li.buscarEmpleado(Integer.parseInt(idEmpleado.getText()));
            if (poscision != - 1) {
                nombre.setText(li.getEmpleados(poscision).getNombre());
                sueldo.setText("$ " + numberFormat.format(li.getEmpleados(poscision).getSalario()));
                fechaIngreso.setText(df.format(li.getEmpleados(poscision).getFechaIngreso()));
                fechaRetiro.setEnabled(true);
                precargarLiquidacion.setEnabled(true);
            } else {
                JOptionPane.showMessageDialog(null, "identificacion de empleado no encontrada por favor intente nuevamente");
                fechaRetiro.setEnabled(false);
                precargarLiquidacion.setEnabled(false);
                nombre.setText("");
                sueldo.setText("");
                fechaIngreso.setText("");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, " Por favor ingrese un numero valido");
        }

    }//GEN-LAST:event_cargarEnpleadoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setVisible(false);
        /**
         * Se pasa la referncia del arreglo empleados dado que al terminar de
         * ejcutar esta instancia se perdera los datos de empleados guardados
         * debido al alcance de la instancia
         */
        Menu menu = new Menu(li.guardarEmpleados());
        menu.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void precargarLiquidacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precargarLiquidacionActionPerformed
        /**
         * Se llaman a los metodo encargados de calcular la seguridad social
         * basandose en la poscion del empleado buscado
         */
        int dias;

        try {
            dias = li.diasTrabajados(df.parse(fechaRetiro.getText()), poscision);
            if (dias >= 0) {
                primaServicio.setText("$ " + numberFormat.format(li.calcularPrimaDeServicio(poscision)));
                cesantias.setText("$ " + numberFormat.format(li.calcularCesantias(poscision)));
                interesesCesantia.setText("$ " + numberFormat.format(li.calcularInteresesCesantias(poscision)));
                vacaciones.setText("$ " + numberFormat.format(li.calcularVacaciones(poscision)));
                totalLiquidacion.setText("$ " + numberFormat.format(li.totalLiquidacion(poscision)));
                guardarLiquidacion.setEnabled(true);
            } else {
                JOptionPane.showMessageDialog(null, "Fecha de retiro anterior a fecha de ingreso por favor validar");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Verifique la fecha de retiro ingresada");
        }
    }//GEN-LAST:event_precargarLiquidacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LiquidarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LiquidarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LiquidarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LiquidarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LiquidarEmpleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cargarEnpleado;
    private javax.swing.JFormattedTextField cesantias;
    private javax.swing.JFormattedTextField fechaIngreso;
    private javax.swing.JFormattedTextField fechaRetiro;
    private javax.swing.JButton guardarLiquidacion;
    private javax.swing.JTextField idEmpleado;
    private javax.swing.JFormattedTextField interesesCesantia;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField nombre;
    private javax.swing.JButton precargarLiquidacion;
    private javax.swing.JFormattedTextField primaServicio;
    private javax.swing.JFormattedTextField sueldo;
    private javax.swing.JFormattedTextField totalLiquidacion;
    private javax.swing.JFormattedTextField vacaciones;
    // End of variables declaration//GEN-END:variables
}
